[package]
name = "snarkvm-synthesizer-stack"
version = "0.12.6"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Stack for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ ]
aleo-cli = [ "colored" ]
serial = [ "console/serial" ]
wasm = [ "console/wasm" ]

[dependencies.circuit]
package = "snarkvm-circuit"
path = "../../circuit"
version = "=0.12.6"

[dependencies.console]
package = "snarkvm-console"
path = "../../console"
version = "=0.12.6"

[dependencies.colored]
version = "2"
optional = true

[dependencies.serde_json]
version = "1.0"
features = [ "preserve_order" ]

[dev-dependencies.bincode]
version = "1"
